apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider-microservice-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: rider-microservice
  template:
    metadata:
      labels:
        component: rider-microservice
    spec:
      containers:
        - name: rider-microservice
          image: rider-microservice:latest
          ports:
            - containerPort: 3001
          env:
            - name: PGUSER
              value: foodking
            - name: PGHOST
              value: user-postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: foodking_rider
            - name: PGPASSWORD
              value: "1234"
            - name: REDIS_HOST
              value: user-redis-cluster-ip-service
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: rider-microservice-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: rider-microservice
  ports:
    - port: 80
      targetPort: 3001
