apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: user-microservice
  template:
    metadata:
      labels:
        component: user-microservice
    spec:
      containers:
        - name: user-microservice
          image: shubhanshu09/user-microservice:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PGUSER
              value: foodking
            - name: PGHOST
              value: user-postgres-cluster-ip-service
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: foodking_user
            - name: PGPASSWORD
              value: "1234"
            - name: REDIS_HOST
              value: user-redis-cluster-ip-service
      imagePullSecrets:
        - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: user-microservice-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: user-microservice
  ports:
    - port: 80
      targetPort: 3000
